version: '3'
services:

  aws-storage:
    image: aws-storage
    build:
      context: ./aws-storage
      dockerfile: Dockerfile
    container_name: video-storage
    ports:
     - "4000:80"
    environment:
      - PORT=80
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:?err}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:?err}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME:?err}
    restart: "no"

  video-streaming:
    image: video-streaming
    build:
      context: ./video-streaming
      dockerfile: Dockerfile
    container_name: video-streaming
    ports:
     - "4001:80"
    environment:
      - PORT=80
      - VIDEO_STORAGE_HOST=video-storage
      - VIDEO_STORAGE_PORT=80
    restart: "no"
