version: '3'
services:

  db:
    image: mongo
    container_name: db
    ports:
      - "4000:27017"
    restart: "always"

  aws-storage:
    image: aws-storage
    build:
      context: ./aws-storage
      dockerfile: Dockerfile-dev
    container_name: video-storage
    volumes:
      - /tmp/aws-storage/npm-cache:/root/.npm:z
      - ./aws-storage/src:/usr/src/app/src:z
      - ./aws-storage/videos:/usr/src/app/videos:z
    ports:
     - "4001:80"
    environment:
      - PORT=80
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:?err}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:?err}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME:?err}
    restart: "no"

  video-streaming:
    image: video-streaming
    build:
      context: ./video-streaming
      dockerfile: Dockerfile-dev
    container_name: video-streaming
    volumes:
      - /tmp/video-streaming/npm-cache:/root/.npm:z
      - ./video-streaming/src:/usr/src/app/src:z
      - ./video-streaming/videos:/usr/src/app/videos:z
    ports:
     - "4002:80"
    environment:
      - PORT=80
      - DBHOST=mongodb://db:27017
      - DBNAME=video-streaming
      - VIDEO_STORAGE_HOST=video-storage
      - VIDEO_STORAGE_PORT=80
    depends_on:
      - db
    restart: "no"

  history:
    image: history
    build:
      context: ./history
      dockerfile: Dockerfile-dev
    container_name: history
    volumes:
      - /tmp/history/npm-cache:/root/.npm:z
      - ./history/src:/usr/src/app/src:z
    ports:
      - "4003:80"
    environment:
      - PORT=80
      - NODE_ENV=development
    restart: "no"